### PR TITLE
Killing a mob with no loots now works

### PR DESCRIPTION
**Pull request by Sceat**
✅ Closes: #364

### CODE REVIEW

**Comment by DeltaEvo** [comment]
I don't think this is a valid fix, a mob should always have a loot array
The one that currently don't have one are:
- hades_horse: Not spawned because hades is not implemented
- hades: Not implemented
- numen_citizen: A NPC, should not be killable
- segeste_citizen: A NPC, should not be killable
- thebes_citizen: A NPC, should not be killable
- guardian: A NPC, should not be killable
- monk: A NPC, should not be killable

**Comment by Sceat** [comment]
wouldn't it be the same to add a loot array in the mob ? this PR just look safer

**Comment by DeltaEvo** [comment]
Yes it would be the same but I'm not asking that, for example for the NPCs I don't wan't to add a loot array because they should not have loots.
This should not be an issue because an NPC should not die
If it die I prefer them server to crash, than for it to continue silently
This commit will just mask the error

**Comment by Sceat** [comment]
then it's fixed with #368

**Pull request closed without merging**
