### PR TITLE
Add support for basic scoreboards

### PR DESCRIPTION
**Pull request by Sceat**
- removed unused fields from ares v1 (stuff never supported)
- polished design

image

### CODE REVIEW

**Comment by Sceat** [comment]
since @Upd4ting went awol, i made a simpler version

**Comment by DeltaEvo** [comment]
> since @Upd4ting went awol, i made a simpler version

Upd4ting didn't went awol, the fault is on me, I just never did the last review of his pr

And is PR is mostly ready for me, I only wanted to change small details on the animation system, I propose that we merge is PR as is since we got already some reviews on his PR that I don't want to redo on yours and that you base your PR on his PR

**Comment by Sceat** [comment]
> > since @Upd4ting went awol, i made a simpler version
> 
> Upd4ting didn't went awol, the fault is on me, I just never did the last review of his pr
> 
> And is PR is mostly ready for me, I only wanted to change small details on the animation system, I propose that we merge is PR as is since we got already some reviews on his PR that I don't want to redo on yours and that you base your PR on his PR

I switched to a reducer (last, next) pattern as it was your concern, still think this PR is leaner and less overkill. Last step i have to do is to switch to chat components

**Comment by Sceat** [comment]
about the CI, not sure i want to deep dive into why `string[].at` doesn't exist in the ts world :/

**Comment by Sceat** [comment]
will work on #55 instead

**Pull request closed without merging**
