### PR TITLE
Remove duplicated player_attributes.observe

### PR DESCRIPTION
**Pull request by ToufouMaster**

### CODE REVIEW

**Comment by ToufouMaster** [comment]
it was not intended to push package files. how can i remove these files?

**Comment by DeltaEvo** [comment]
It seems that you added sceat's commit as well, removing it should remove the two package files

**Comment by ToufouMaster** [comment]
how?

**Comment by DeltaEvo** [comment]
There is multiple ways (in my personal order of preference):
- drop the commit during a `git rebase --interactive`
- reset you branch to origin/master and cherry-pick the commit that you want
- revert the commit that you don't want and squash all 3 commits together

**Review by Sceat — CHANGES_REQUESTED** [review]
https://github.com/aresrpg/aresrpg/pull/549#issuecomment-1327982202

**Review by Sceat — APPROVED** [review]

**Comment by Sceat** [comment]
blyat you have the bypass rights

**Pull request merged**
